global_args:
  trainer_backend: pl
  enable_deepspeed: false
  enable_ptv2: false
  enable_lora: true
  load_in_bit: 0
  config_merge: {}
  # 模型权重 ， 对应 config.constant_map.py
  model_name: Qwen2.5-1.5B

  # one of auto 16 bf16 32
  precision: auto
  quantization_config:
    load_in_8bit: false
    load_in_4bit: false
    llm_int8_threshold: 6.0
    llm_int8_has_fp16_weight: false
    bnb_4bit_compute_dtype: float16  # one of float16  bfloat16 float32
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4


# qwen 模型 >= 1.5 均可在下面添加

global_models_mapper:

    Qwen2.5-1.5B:
        model_type: qwen
        model_name_or_path: /data/nlp/pre_models/torch/qwen/Qwen2.5-1.5B-Instruct
        config_name: /data/nlp/pre_models/torch/qwen/Qwen2.5-1.5B-Instruct
        tokenizer_name: /data/nlp/pre_models/torch/qwen/Qwen2.5-1.5B-Instruct
    
    Qwen1.5-1.8B-Chat:
      model_type: qwen2
      model_name_or_path: /data/nlp/pre_models/torch/qwen2/Qwen1.5-1.8B-Chat
      config_name: /data/nlp/pre_models/torch/qwen2/Qwen1.5-1.8B-Chat
      tokenizer_name: /data/nlp/pre_models/torch/qwen2/Qwen1.5-1.8B-Chat

    Qwen1.5-MoE-A2.7B:
      model_type: qwen2_moe
      model_name_or_path: /data/nlp/pre_models/torch/qwen2/Qwen1.5-MoE-A2.7B
      config_name: /data/nlp/pre_models/torch/qwen2/Qwen1.5-MoE-A2.7B
      tokenizer_name: /data/nlp/pre_models/torch/qwen2/Qwen1.5-MoE-A2.7B

